title: 1GymholRadio Status
languageCode: en
params:
  shortDateFormat: 15:04 — Jan 2
  meta_description: ""
  systems:
    - name: Website
      description: ""
      link: https:1gymholradio.gr
    - name: Audio server 1
      description: ""
      link: ""
    - name: Audio server 2
      link: https://1gymholradio.radiostream321.com/
  dateFormat: January 2, 2006 at 3:04 PM
  disqusShortname: null
  timezoneString: " UTC"
  logo: /images/clearstatus.svg
  description_header: ""
  copyrightHolder: 1GymholRadio
  eventsPerPage: 10
  iconType: image/png
  icon: /images/clearstatus.png
  description_footer: ""
